---
abstract: 'Detect running under terminal (and get terminal emulator information)'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-Detect
requires:
  SHARYANTO::Proc::Util: 0.44
  experimental: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Term-Detect
  repository: http://github.com/sharyanto/perl-Term-Detect
version: 0.07
